apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: euty5pryn-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-370f4a6dbe.qfqm.p3.openshiftapps.com/rhtap/rhtap-qe:eb26a754fc269952278d0d1b04de44e2009b348f@sha256:7562a2b9091e4aac3a9cfcb1148796cf7813b1e191cf181d31841635bf7aeb44
          name: container-image
